# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

knife4j:
  enable: true
  setting:
    custom-code: 500
    enable-footer-custom: false
    
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: maku-boot
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  flyway:
    #是否开启
    enabled: true
    #迁移脚本的位置，默认db/db
    locations: classpath:db/migration
    #是否允许无序的迁移
    out-of-order: true
    #当初始化好连接时要执行的SQL
    #init-sqls:
    #使用的元数据表名-->版本记录
    table: zz_flyway_schema_history
    # 历史工程接入时，需要设定true
    baseline-on-migrate: true
    baseline-version: 0

storage:
  enabled: true
  config:
    # 存储类型：local、aliyun、tencent、qiniu、huawei、minio
    type: local
    domain: http://localhost:8080
  local:
    path: D://upload

maku:
  xss:
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: net.maku.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

#easy trans 数据翻译组件
easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: false
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #启用平铺模式
  is-enable-tile: true